add mcp data-commons add change mcp context7 configuration to use a launcher, because npx need PATH value modified before launch

diff --git a/iatools b/iatools
--- a/iatools
+++ b/iatools
@@ -31,7 +31,8 @@ Options:
     gc mcp calculator install|uninstall         Add mcp-calculator local server configuration.
     gc mcp github install|uninstall             Add mcp-github remote server configuration.
     gc mcp desktop-commander install|uninstall  Add mcp-desktop-commander local server configuration.
-    gc mcp context7 install|uninstall           Add mcp-context7 local server configuration.
+    gc mcp context7 install|uninstall   [CONTEXT7_API_KEY]        Add mcp-context7 local server configuration. Provide optional CONTEXT7_API_KEY as environment variable or command argument.
+    gc mcp data commons install|uninstall [DC_API_KEY]          Add mcp-data-commons remote server configuration. Provide mandatory DC_API_KEY from https://apikeys.datacommons.org/ as environment variable or command argument.
 
     ----
     npm-config set <key> <value>    Set a npm configuration for the internal nodejs.
@@ -53,6 +54,9 @@ EOF
 iatools_path() {
     export IATOOLS_LAUNCHER_HOME="${STELLA_APP_WORK_ROOT}/launcher"
     mkdir -p "${IATOOLS_LAUNCHER_HOME}"
+
+    export IATOOLS_MCP_LAUNCHER_HOME="${IATOOLS_LAUNCHER_HOME}/mcp"
+    mkdir -p "${IATOOLS_MCP_LAUNCHER_HOME}"
 
     export IATOOLS_ISOLATED_DEPENDENCIES_ROOT="${STELLA_APP_WORK_ROOT}/isolated_dependencies"
     mkdir -p "${IATOOLS_ISOLATED_DEPENDENCIES_ROOT}"
@@ -80,7 +84,7 @@ runtime_path() {
     if check_requirements "python" "VERBOSE"; then
         export IATOOLS_PYTHON_BIN_PATH="${IATOOLS_ISOLATED_DEPENDENCIES_ROOT}/miniforge3/bin/"
     else
-        # we use an already installed nodejs, not iatools nodejs
+        # we use an already installed python, not iatools python
         export IATOOLS_PYTHON_BIN_PATH=""
     fi
 
@@ -404,6 +408,37 @@ main() {
     if [ ! "$mcp_name" = "" ]; then
         [ "$action" = "" ] && echo " -- ERROR : action missing" && exit 1
         case "$mcp_name" in
+            data-commons)
+                echo " -- data-commons"
+                if ! check_requirements "python"; then echo " -- ERROR : python missing, launch iatools init"; exit 1; fi;             
+                case "$action" in
+                    "install")
+                        echo "    Configuring"
+                        [ ! -z "$3" ] && export DC_API_KEY="$3"
+                        if [ -z "$DC_API_KEY" ]; then
+                            echo " -- ERROR : missing Data Commons API key"
+                            echo "    Provide a DC_API_KEY environment variable OR as third argument of the command"
+                            echo "    You can get one from https://apikeys.datacommons.org/"
+                            exit 1
+                        fi
+                        echo "    Provided DC_API_KEY for Data Commons API key from https://apikeys.datacommons.org/ : $DC_API_KEY"
+                        case "$command" in
+                            "gc")gemini_merge_config "${_CURRENT_FILE_DIR}/pool/mcp-servers/data-commons/gemini-cli/settings.json";;
+                            "oc")echo " -- ERROR : not supported";exit 1;;
+                            *)echo " -- ERROR : missing or unknown target $command";exit 1;;
+                        esac
+                        echo "    Configuration has been added"
+                        ;;
+                    "uninstall")
+                        echo "    Reset configuration"
+                        case "$command" in
+                            "gc")gemini_remove_config "mcpServers.data-commons";;
+                            "oc")echo " -- ERROR : not supported";exit 1;;
+                            *)echo " -- ERROR : missing or unknown target $command";exit 1;;
+                        esac
+                        ;;
+                esac
+                ;;
             desktop-commander)
                 echo " -- mcp-desktop-commander"
                 if ! check_requirements "nodejs"; then echo " -- ERROR : nodejs missing, launch iatools init"; exit 1; fi;             
@@ -464,6 +499,13 @@ main() {
                 case "$action" in
                     "install")
                         echo "    Configuring"
+                        echo '#!/bin/sh' > "${IATOOLS_MCP_LAUNCHER_HOME}/context7"
+                        echo "export PATH=\"${IATOOLS_NODEJS_BIN_PATH}:\${PATH}\"" >> "${IATOOLS_MCP_LAUNCHER_HOME}/context7"
+                        echo "exec \"npx\" -y @upstash/context7-mcp --api-key \"\${CONTEXT7_API_KEY}\"" >> "${IATOOLS_MCP_LAUNCHER_HOME}/context7"
+                        chmod +x "${IATOOLS_MCP_LAUNCHER_HOME}/context7"
+
+                        [ ! -z "$3" ] && export CONTEXT7_API_KEY="$3"                        
+                        echo "    Provided optional CONTEXT7_API_KEY : $CONTEXT7_API_KEY"
                         case "$command" in
                             "gc")gemini_merge_config "${_CURRENT_FILE_DIR}/pool/mcp-servers/context7/gemini-cli/settings.json";;
                             "oc")opencode_merge_config "${_CURRENT_FILE_DIR}/pool/mcp-servers/context7/opencode/opencode.json";;
@@ -473,8 +515,9 @@ main() {
                         ;;
                     "uninstall")
                         echo "    Reset configuration"
+                        rm -f "${IATOOLS_MCP_LAUNCHER_HOME}/context7"
                         case "$command" in
-                            "gc")ggemini_remove_config "mcpServers.context7";;
+                            "gc")gemini_remove_config "mcpServers.context7";;
                             "oc")opencode_remove_config "mcp.context7";;
                             *)echo " -- ERROR : missing or unknown target $command";exit 1;;
                         esac
